### ISSUE TITLE
Crypto 101

### ISSUE THREAD

**Issue by yjaquinas** [robinrheem/thehodl#6]
# Crypto 101
Materials to catch up the basic knowledge about blockchain & cryptocurrency :coin:

## Videos

<details><summary>a16z Crypto Startup School</summary><div markdown="1">

>Learn How to Build a Crypto Company
The course videos from a16z’s Crypto Startup School, held in the spring of 2020, are now available to all.

[a16z Crypto Startup School](https://a16z.com/crypto-startup-school/)
- [x] [Chris Dixon: Crypto Networks and Why They Matter](https://www.youtube.com/watch?v=2wxtiNgXBaU&list=PLM4u6XbiXf5oDP6DFeEoNP5K_Epy1RAx4&index=2&t=1s)
- [x] [Dan Boneh: Blockchain Primitives: Cryptography and Consensus](https://www.youtube.com/watch?v=V0JdeRzVndI&list=PLM4u6XbiXf5oDP6DFeEoNP5K_Epy1RAx4&index=3&t=650s)
- [x] [Brian Armstrong: Setting Up and Scaling a Crypto Company](https://www.youtube.com/watch?v=VL5V16HAjYA&list=PLM4u6XbiXf5oDP6DFeEoNP5K_Epy1RAx4&index=5)
- [x] [Balaji Srinivasan: Applications: Today & 2025](https://www.youtube.com/watch?v=3jPYk7ucrjo&list=PLM4u6XbiXf5oDP6DFeEoNP5K_Epy1RAx4&index=6)
- [x] [Josh Williams: Opportunities for Crypto in Gaming](https://www.youtube.com/watch?v=CBu8lLC0g8I&list=PLM4u6XbiXf5oDP6DFeEoNP5K_Epy1RAx4&index=7)
- [x] [Ali Yahya: Crypto Business Models](https://www.youtube.com/watch?v=AI1N6dY8vSQ&list=PLM4u6XbiXf5oDP6DFeEoNP5K_Epy1RAx4&index=8)
- [x] [Sam Williams: Mechanism Design 101](https://www.youtube.com/watch?v=gCFlGLbI_kE&list=PLM4u6XbiXf5oDP6DFeEoNP5K_Epy1RAx4&index=9)
- [ ] ~~[Tom Preston-Werner with Chris Dixon: Building Companies and Developer Communities](https://www.youtube.com/watch?v=gK-7GUS8G-Q&list=PLM4u6XbiXf5oDP6DFeEoNP5K_Epy1RAx4&index=10)~~
- [x] [Robert Leshner and Jesse Walden: Deep Dive on Decentralization](https://www.youtube.com/watch?v=rW8GrxQYPbI&list=PLM4u6XbiXf5oDP6DFeEoNP5K_Epy1RAx4&index=11)
- [ ] ~~[Tina Ferguson: Managing Distributed Workforces](https://www.youtube.com/watch?v=HXMnut5m8_M&list=PLM4u6XbiXf5oDP6DFeEoNP5K_Epy1RAx4&index=12)~~
- [x] [Jutta Steiner: Secure Smart Contract Development](https://www.youtube.com/watch?v=bI45YonLK0Q&list=PLM4u6XbiXf5oDP6DFeEoNP5K_Epy1RAx4&index=13)
- [ ] [Nitya Subramanian: Products and Protocol](https://www.youtube.com/watch?v=cNya3Ha-KpI&list=PLM4u6XbiXf5oDP6DFeEoNP5K_Epy1RAx4&index=14)
- [ ] [Jesse Walden: Fundraising and Deal Structure](https://www.youtube.com/watch?v=jNbPriRubUs&list=PLM4u6XbiXf5oDP6DFeEoNP5K_Epy1RAx4&index=15)
- [ ] [Brian Brooks: Token Securities Framework and Launching a Network](https://www.youtube.com/watch?v=CrrcGiyPglI&list=PLM4u6XbiXf5oDP6DFeEoNP5K_Epy1RAx4&index=16)
</div></details>

<details><summary>Decentralized tech - Simply Explained (2017 - 2019)</summary><div markdown="1">

[Decentralized tech - Simply Explained](https://www.youtube.com/playlist?list=PLzvRQMJ9HDiSM_uLyxy5B6ml_BpmLFAHU)
- [x] [How does a blockchain work - Simply Explained](https://www.youtube.com/watch?v=SSo_EIwHSd4&list=PLzvRQMJ9HDiSM_uLyxy5B6ml_BpmLFAHU&index=14)
- [x] [Smart contracts - Simply Explained](https://www.youtube.com/watch?v=ZE2HxTmxfrI&list=PLzvRQMJ9HDiSM_uLyxy5B6ml_BpmLFAHU&index=13)
- [x] [What is a Bitcoin hard fork? Simply Explained!](https://www.youtube.com/watch?v=XCo6yyutYAM&list=PLzvRQMJ9HDiSM_uLyxy5B6ml_BpmLFAHU&index=12)
- [x] [Bitcoin's Lightning Network, Simply Explained!](https://www.youtube.com/watch?v=rrr_zPmEiME&list=PLzvRQMJ9HDiSM_uLyxy5B6ml_BpmLFAHU&index=11)
- [x] [IOTA's Tangle - Simply Explained](https://www.youtube.com/watch?v=CZxH1V_zoug&list=PLzvRQMJ9HDiSM_uLyxy5B6ml_BpmLFAHU&index=10)
- [x] [Cardano - Simply Explained](https://www.youtube.com/watch?v=Do8rHvr65ZA&list=PLzvRQMJ9HDiSM_uLyxy5B6ml_BpmLFAHU&index=9)
- [x] [ERC20 tokens - Simply Explained](https://www.youtube.com/watch?v=cqZhNzZoMh8&list=PLzvRQMJ9HDiSM_uLyxy5B6ml_BpmLFAHU&index=8)
- [x] [Proof-of-Stake (vs proof-of-work)](https://www.youtube.com/watch?v=M3EFi_POhps&list=PLzvRQMJ9HDiSM_uLyxy5B6ml_BpmLFAHU&index=7)
- [x] [IPFS: Interplanetary file storage!](https://www.youtube.com/watch?v=5Uj6uR3fp-U&list=PLzvRQMJ9HDiSM_uLyxy5B6ml_BpmLFAHU&index=6)
- [x] [Blockchains: how can they be used? (Use cases for Blockchains)](https://www.youtube.com/watch?v=aQWflNQuP_o&list=PLzvRQMJ9HDiSM_uLyxy5B6ml_BpmLFAHU&index=5)
- [x] [Ethereum's Constantinople Update & Difficulty Bomb](https://www.youtube.com/watch?v=rfg408lSAj0&list=PLzvRQMJ9HDiSM_uLyxy5B6ml_BpmLFAHU&index=4)
- [x] [Blockchain & Smart contracts: Digital Evolution Conference 2018](https://www.youtube.com/watch?v=HNCwbKAY7AM&list=PLzvRQMJ9HDiSM_uLyxy5B6ml_BpmLFAHU&index=3)
- [x] [Distributed social media - Mastodon & Fediverse Explained](https://www.youtube.com/watch?v=S57uhCQBEk0&list=PLzvRQMJ9HDiSM_uLyxy5B6ml_BpmLFAHU&index=2)
- [x] [How Bitcoin Wallets Work (Public & Private Key Explained)](https://www.youtube.com/watch?v=GSTiKjnBaes&list=PLzvRQMJ9HDiSM_uLyxy5B6ml_BpmLFAHU&index=1&t=2s)
- [x] [Creating a blockchain with Javascript (Blockchain, part 1)](https://www.youtube.com/watch?v=zVqczFZr124&list=PLzvRQMJ9HDiSM_uLyxy5B6ml_BpmLFAHU&index=15)
- [ ] [Implementing Proof-of-Work in Javascript (Blockchain, part 2)](https://www.youtube.com/watch?v=HneatE69814&list=PLzvRQMJ9HDiSM_uLyxy5B6ml_BpmLFAHU&index=16)
- [ ] [Mining rewards & transactions - Blockchain in Javascript (part 3)](https://www.youtube.com/watch?v=fRV6cGXVQ4I&list=PLzvRQMJ9HDiSM_uLyxy5B6ml_BpmLFAHU&index=17)
- [ ] [Signing transactions - Blockchain in Javascript (part 4)](https://www.youtube.com/watch?v=kWQ84S13-hw&list=PLzvRQMJ9HDiSM_uLyxy5B6ml_BpmLFAHU&index=18)
</div></details>

<details><summary>Blockchain & Cryptocurrency</summary><div markdown="1">

[Blockchain & Cryptocurrency](https://www.youtube.com/playlist?list=PLzvRQMJ9HDiQF_5bEErheiAawrJ-2zQoI)
- [ ] [NFT's Explained in 4 minutes!](https://www.youtube.com/watch?v=FkUn86bH34M&list=PLzvRQMJ9HDiQF_5bEErheiAawrJ-2zQoI&index=1)
- [ ] [Mining Difficulty - Simply Explained](https://www.youtube.com/watch?v=o1gOyhU6XEw&list=PLzvRQMJ9HDiQF_5bEErheiAawrJ-2zQoI&index=2)
- [ ] [Is Bitcoin Valuable?](https://www.youtube.com/watch?v=IjEw5uwg-Qc&list=PLzvRQMJ9HDiQF_5bEErheiAawrJ-2zQoI&index=3)
- [ ] [How Bitcoin Wallets Work (Public & Private Key Explained)](https://www.youtube.com/watch?v=GSTiKjnBaes&list=PLzvRQMJ9HDiQF_5bEErheiAawrJ-2zQoI&index=4)
- [ ] [Zero Knowledge Proof - ZKP](https://www.youtube.com/watch?v=OcmvMs4AMbM&list=PLzvRQMJ9HDiQF_5bEErheiAawrJ-2zQoI&index=5)
- [ ] [Will GDPR kill blockchains?](https://www.youtube.com/watch?v=5I3wYAwbKMM&list=PLzvRQMJ9HDiQF_5bEErheiAawrJ-2zQoI&index=6)
- [ ] [Blockchain & Smart contracts: Digital Evolution Conference 2018](https://www.youtube.com/watch?v=HNCwbKAY7AM&list=PLzvRQMJ9HDiQF_5bEErheiAawrJ-2zQoI&index=7)
- [ ] [Blockchains: how can they be used? (Use cases for Blockchains)](https://www.youtube.com/watch?v=aQWflNQuP_o&list=PLzvRQMJ9HDiQF_5bEErheiAawrJ-2zQoI&index=8)
- [ ] [IPFS: Interplanetary file storage!](https://www.youtube.com/watch?v=5Uj6uR3fp-U&list=PLzvRQMJ9HDiQF_5bEErheiAawrJ-2zQoI&index=9)
- [ ] [Proof-of-Stake (vs proof-of-work)](https://www.youtube.com/watch?v=M3EFi_POhps&list=PLzvRQMJ9HDiQF_5bEErheiAawrJ-2zQoI&index=10)
- [ ] [ERC20 tokens - Simply Explained](https://www.youtube.com/watch?v=cqZhNzZoMh8&list=PLzvRQMJ9HDiQF_5bEErheiAawrJ-2zQoI&index=11)
- [ ] [Cardano - Simply Explained](https://www.youtube.com/watch?v=Do8rHvr65ZA&list=PLzvRQMJ9HDiQF_5bEErheiAawrJ-2zQoI&index=12)
- [ ] [IOTA's Tangle - Simply Explained](https://www.youtube.com/watch?v=CZxH1V_zoug&list=PLzvRQMJ9HDiQF_5bEErheiAawrJ-2zQoI&index=13)
- [ ] [Bitcoin's Lightning Network, Simply Explained!](https://www.youtube.com/watch?v=rrr_zPmEiME&list=PLzvRQMJ9HDiQF_5bEErheiAawrJ-2zQoI&index=14)
- [ ] [What is a Bitcoin hard fork? Simply Explained!](https://www.youtube.com/watch?v=XCo6yyutYAM&list=PLzvRQMJ9HDiQF_5bEErheiAawrJ-2zQoI&index=15)
- [ ] [Smart contracts - Simply Explained](https://www.youtube.com/watch?v=ZE2HxTmxfrI&list=PLzvRQMJ9HDiQF_5bEErheiAawrJ-2zQoI&index=16)
- [ ] [How does a blockchain work - Simply Explained](https://www.youtube.com/watch?v=SSo_EIwHSd4&list=PLzvRQMJ9HDiQF_5bEErheiAawrJ-2zQoI&index=17)
</div></details>

## Books

- [ ] [Mastering Bitcoin](https://github.com/bitcoinbook/bitcoinbook)
- [ ] [Mastering Ethereum](https://github.com/ethereumbook/ethereumbook)

**Comment by RobinRheem** [comment]
Ooooh noice, you're doing great!

**Comment by RobinRheem** [comment]
I'll add some stuff over here so your learning keeps on getting topped on lol
